name: Unit Tests
on: pull_request

env:
  POETRY_URL: https://install.python-poetry.org

jobs:
  # Label
  unittest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: [ "3.12", "3.13" ]
        DATABASE: [ "sqlite" ]
        split: [ "1", "2", "3", "4", "5", "6", "7", "8" ]  # Number of splits for pytest-split

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out code
        uses: actions/checkout@v5
        with:
          lfs: 'true'

      # SQLite/SpatiaLite specific setup
      - name: Install SpatiaLite
        if: matrix.DATABASE == 'sqlite'
        run: |
          sudo apt install -y libsqlite3-mod-spatialite

      - name: Set up Python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install Dependencies
        run: |
          poetry install --no-root

      - name: Run Tests
        run:
           poetry run pytest --splits 8 --group ${{ matrix.split }} --store-durations tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          OPENROUTESERVICE_API_KEY: ${{ secrets.OPENROUTESERVICE_API_KEY }}
          OPENROUTESERVICE_BASE_URL: "https://api.openrouteservice.org/"
          SPATIALITE_LIBRARY_PATH: "/usr/lib/x86_64-linux-gnu/mod_spatialite"
          # The DATABASE_URL is set conditionally above

      - name: Upload durations
        uses: actions/upload-artifact@v6
        with:
          include-hidden-files: 'true'
          name: test-durations-${{ matrix.split }}
          path: .test_durations